camera_id: YT_LIVE_TEST
coordinate_space: original_frame
frame_size:
  width: 1280
  height: 720
zones:
- zone_id: zone_1
  name: ''
  polygon:
  - - 0.0
    - 307.0
  - - 5.0
    - 715.0
  - - 859.0
    - 712.0
  - - 890.0
    - 166.0
  - - 577.0
    - 149.0
