camera_id: YT_LIVE_TEST
coordinate_space: original_frame
frame_size:
  width: 1280
  height: 720
lanes:
- lane_id: lane_1
  name: ''
  polygon:
  - - 3.0
    - 304.0
  - - 2.0
    - 577.0
  - - 774.0
    - 161.0
  - - 577.0
    - 148.0
- lane_id: lane_2
  name: ''
  polygon:
  - - 1.0
    - 576.0
  - - 5.0
    - 712.0
  - - 856.0
    - 714.0
  - - 889.0
    - 165.0
  - - 773.0
    - 160.0
